name: ramatranstravel.com

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      run: |
          cd /home/ramatranstravel/htdocs/ramatranstravel.com
          git checkout -f
          git pull
    - name: clear cache proccess
      run : | 
          cd /home/ramatranstravel/htdocs/ramatranstravel.com
          php artisan cache:clear
          php artisan config:clear
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: restart app run
      run : systemctl restart nginx
